const products = [
  {
    id: 1,
    uptitle: 'Сказочное заморское яство',
    name: 'Нямушка',
    taste: 'с фуа-гра',
    weight: '0,5',
    servings: '10 порций',
    toys: 'мышь в подарок',
    note: null,
    description: 'Печень утки разварная с артишоками.',
    descDisabled: 'Печалька, с фуа-гра закончился.',
    disabled: false,
  },
  {
    id: 2,
    uptitle: 'Сказочное заморское яство',
    name: 'Нямушка',
    taste: 'c рыбой',
    weight: 2,
    servings: '40 порций',
    toys: '2 мыши в подарок',
    note: null,
    description: 'Головы щучьи с чесноком да свежайшая сёмгушка.',
    descDisabled: 'Печалька, с рыбой закончился.',
    disabled: false,
  },
  {
    id: 3,
    uptitle: 'Сказочное заморское яство',
    name: 'Нямушка',
    taste: 'c курой',
    weight: 5,
    servings: '100 порций',
    toys: '5 мышей в подарок',
    note: 'заказчик доволен',
    description: 'Филе из цыплят с трюфелями в бульоне.',
    descDisabled: 'Печалька, с курой закончился.',
    disabled: true,
  },
]

export default products
